server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/courseapi
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
