name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 9 * * 2'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate
        uses: docker://renovate/renovate:34.158.1-slim
        env:
          DRY_RUN: ${{ github.event_name == 'pull_request' && true || false }}
#          HTTPS_PROXY: http://proxy.ctonetwrkprod.aws.dsarena.com:3128
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_BINARY_SOURCE: install
          LOG_LEVEL: debug
        with:
          args: MzwandileMdladla/rest-api --dry-run=${{ env.DRY_RUN }} --onboarding=false
          
